//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballInspector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string League { get; set; }
        public int Points { get; set; }
        public int Wins { get; set; }
        public int Draws { get; set; }
        public int Defeats { get; set; }
        public int ScoredGoals { get; set; }
        public int LostGoals { get; set; }
        public int GoalDifference { get; set; }


        public override string ToString()
        {
            return this.Name + " (" +  this.League + ")";
        }
    }
}
